version: "3"

services:
  contractor-server:
    container_name: "contractor-server"
    image: pefpi/contractor-server
    restart: always
    tty: true
    ports:
      - 3002:8080
    expose:
      - 3002
    links:
      - contractor-web
    networks:
      - code-network
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_DATA=${DATABASE_DATA}

  contractor-client:
    container_name: "contractor-client"
    image: pefpi/contractor-client
    command: "node"
    volumes:
      - ./contractor-client/build:/xxx/xxx

  contractor-web:
    image: nginx
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - code-network
    volumes:
      - ./contractor-client/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  code-network:
    external:
      name: code-network
